# fly.toml app configuration file generated for elixir-cdn-litefs on 2023-07-28T17:28:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elixir-cdn-litefs"
primary_region = "gru"
kill_signal = "SIGTERM"
# swap_size_mb = 512

# [deploy]
#   release_command = "/app/bin/migrate"

[env]
  PRIMARY_REGION = "gru"
  PHX_HOST = "elixir-cdn-litefs.fly.dev"
  PORT = "4000"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
